main: me.s1mple.matrix.Matrix
name: MatrixPlugin
version: ${project.version}
author: S1mple, CrashCringle12
depend: [LuckPerms, LibsDisguises, VampireRevamp, SkillsPro, CustomDimensions]
description: Matrix Plugin.
api-version: 1.14
commands:
  matrix:
    description: Shows help on the plugin.
  arenamanager:
    description: Handles the arena manager
    aliases:
      - am
  tournament:
    description: Basic tournament command.
    aliases:
      - tt