main: me.s1mple.matrix.Matrix
name: MatrixPlugin
version: ${project.version}
author: Simple
depend: [ProjectKorra, AuthMe, AdvancedAchievements, PermissionsEx]
description: Matrix Abilities.
api-version: 1.13
commands:
  matrix:
    description: Shows help on the plugin.
  battlepass:
    description: Shows battlepass menu.