main: me.s1mple.matrix.Matrix
name: MatrixPlugin
version: ${project.version}
author: CrashCringle12, S1mple
softdepend: [LuckPerms, LibsDisguises, VampireRevamp, SkillsPro, CringleBosses]
description: Matrix Plugin.
api-version: 1.18
commands:
  matrix:
    description: Shows help on the plugin.
  arenamanager:
    description: Handles the arena manager
    aliases:
      - am
  tournament:
    description: Basic tournament command.
    aliases:
      - tt