main: me.s1mple.matrix.Matrix
name: MatrixPlugin
version: ${project.version}
author: S1mple, CrashCringle12
depend: [ProjectKorra, SkillsPro, VampireRevamp, LuckPerms, WorldEdit, LibsDisguises]
description: Matrix Plugin.
api-version: 1.13
commands:
  matrix:
    description: Shows help on the plugin.
  arenamanager:
    description: Handles the arena manager
    aliases:
      - am